### ISSUE TITLE
cannot setup with npm package

### ISSUE THREAD

**Issue by kazupon** [azu/github-label-setup#6]
I've tried to setup with [npm package](https://github.com/kazupon/github-label-preset
).
However, occured in the following error, I could not setup ... 😞 

```
github-label-setup --labels @kazupon/github-label-preset
Error: Not found label: @kazupon/github-label-preset
    at /path/to/users/my/bin/.nvm/versions/node/v11.13.0/lib/node_modules/@azu/github-label-setup/lib/github-label-setup.js:58:19

  GitHub label setup script.

  Usage
    $ github-label-setup --token xxx

  Options

    -h, --help                  output usage information
    -l, --labels <path>         the path to look for the label configuration in. Default: labels.json
    --token <token>  a GitHub access token (also settable with a GITHUB_ACCESS_TOKEN environment variable)
    -d, --dry-run               calculate the required label changes but do not apply them
    -A, --allow-added-labels    allow additional labels in the repo, and don't delete them
```

In [`Npm packages for labels` section](https://github.com/azu/github-label-setup#npm-packages-for-labels), it's written the following:

>labels can be set requireable path like npm packages.

I believe that can `require` path like npm packages.

**Comment by azu** [comment]
https://github.com/azu/github-label-setup/blob/5b6b8eeb7acafa8e0169f5f4fcebe8ec08f9d5f5/src/github-label-setup.js#L54

Currently, It just `require(<labels path>)`.

Workadound:

```
npm install -g @kazupon/github-label-preset
github-label-setup --labels @kazupon/github-label-preset
```

I think that we have two approach to resolve this issue

- Add the workaround if success to README
- Use npm CDN like unpkg https://unpkg.com/@kazupon/github-label-preset
  - Just fetch the package
- Imeplemt pkg manger using [pacote](https://github.com/npm/pacote)

We welcome to Pull Request!

📝 I like to separate option name `--labels` and `--label-pkg`?

**Comment by azu** [comment]
Onliner using `npx`

```
npx -p @azu/github-label-setup -p @kazupon/github-label-preset github-label-setup --token $GITHUB_TOKEN --labels @kazupon/github-label-preset
```

**Comment by kazupon** [comment]
That one-liner is a good idea.
There is a workaround, so close it.

Thanks!
